name: Unified Multi-Account Commit Workflow (Safe Version)

on:
  workflow_dispatch:
    inputs:
      total_commits:
        description: "Jumlah total commit per akun"
        default: 1650
      total_days:
        description: "Jumlah hari pembagian commit"
        default: 365
      target_repo:
        description: "Repository utama tempat commit dilakukan (format: owner/repo)"
        default: "safarovnatiq/hapus"

jobs:
  commit-only:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        include:
          - account: SafarovNatiq
            email: 97017190+SafarovNatiq@users.noreply.github.com
            token_secret: PAT1
          - account: miri-rodriguezg
            email: 33882180+miri-rodriguez@users.noreply.github.com
            token_secret: PATnew
          - account: davi709
            email: 67561050+davi709@users.noreply.github.com
            token_secret: PAT3
          - account: fahDkeerapak
            email: 125784790+fahDkeerapak@users.noreply.github.com
            token_secret: PAT4
          - account: zhanglei0031
            email: 91275664+zhanglei0031@users.noreply.github.com
            token_secret: PAT5
          - account: Veluste
            email: 10331502+Veluste@users.noreply.github.com
            token_secret: PAT6
          - account: sjj370817
            email: 91030827+sjj370817@users.noreply.github.com
            token_secret: PAT7
          - account: titotito12
            email: 17217284+titotito12@users.noreply.github.com
            token_secret: PAT8
          - account: luischalo74
            email: 143030870+luischalo74@users.noreply.github.com
            token_secret: PAT9
          - account: selmanuslu
            email: 63121832+selmanuslu@users.noreply.github.com
            token_secret: PAT10
          - account: greativann
            email: 139834460+greativann@users.noreply.github.com
            token_secret: PAT11
          - account: vegeta888
            email: 19150937+vegeta888@users.noreply.github.com
            token_secret: PAT12
          - account: Samikhanzada
            email: 141436265+Samikhanzada@users.noreply.github.com
            token_secret: PAT13
          - account: Fel65
            email: 93129277+Fel65@users.noreply.github.com
            token_secret: PAT15
          - account: RockawayGio
            email: 138243063+RockawayGio@users.noreply.github.com
            token_secret: PAT16

    steps:
      - name: Delay before account start
        run: |
          DELAY=$((10 + RANDOM % 10))
          echo "🕒 Menunggu $DELAY detik sebelum memulai akun ${{ matrix.account }}..."
          sleep $DELAY

      - name: Clone target repo
        env:
          GH_TOKEN: ${{ secrets[matrix.token_secret] }}
          TARGET_REPO: ${{ github.event.inputs.target_repo }}
        run: |
          echo "=== Cloning target repo ==="
          git clone https://x-access-token:${GH_TOKEN}@github.com/$TARGET_REPO repo
          cd repo
          git config user.name "${{ matrix.account }}"
          git config user.email "${{ matrix.email }}"
          echo "✅ Git identity configured for ${{ matrix.account }}"

      - name: Generate distributed commits
        env:
          TOTAL_COMMITS: ${{ github.event.inputs.total_commits }}
          TOTAL_DAYS: ${{ github.event.inputs.total_days }}
          GH_TOKEN: ${{ secrets[matrix.token_secret] }}
          TARGET_REPO: ${{ github.event.inputs.target_repo }}
        run: |
          cd repo
          mkdir -p logs

          COMMITS_PER_DAY=$((TOTAL_COMMITS / TOTAL_DAYS))
          START_DATE=$(date -d "$TOTAL_DAYS days ago" +%Y-%m-%d)
          echo "📊 $TOTAL_COMMITS commits over $TOTAL_DAYS days ($COMMITS_PER_DAY/day)"
          echo ""

          for ((day=0; day<TOTAL_DAYS; day++)); do
            DATE_STR=$(date -d "$START_DATE +$day days" +%Y-%m-%d)
            for ((i=1; i<=COMMITS_PER_DAY; i++)); do
              echo "Commit $i oleh ${{ matrix.account }} pada $DATE_STR" >> logs/${{ matrix.account }}_commit_$day.txt
              git add logs/${{ matrix.account }}_commit_$day.txt
              GIT_COMMITTER_DATE="$DATE_STR 12:00:00" \
              GIT_AUTHOR_DATE="$DATE_STR 12:00:00" \
              git commit -m "Auto commit $i by ${{ matrix.account }}" || true
            done
          done

          echo "🚀 Pushing commits..."
          for attempt in {1..3}; do
            git push https://x-access-token:${GH_TOKEN}@github.com/$TARGET_REPO HEAD:main && break || sleep 3
          done
          echo "✅ Commits pushed for ${{ matrix.account }}"
